# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

dist: bionic
language: r
sudo: true
before_install:
  - sudo add-apt-repository -y ppa:c2d4u.team/c2d4u4.0+
  - sudo apt-get -q update
r_binary_packages:
  - stringi
  - stringr
  - devtools
  - rmarkdown
  - bibtex
  - knitr
bioc_required: true
cache: packages
r:
  - release
  - devel
warnings_are_errors: false
